###
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "id": "1",
    "nombre": "Beatriz",
    "correo": "beatriz@live.u-tad.com",
    "nickname": "ProFisica",
    "instrumento": "violin",
    "bio": "Estudiante de U-tad",
    "horario": "Lunes 10:00-12:00",
}

###
GET http://localhost:3000/api/tracks HTTP/1.1
###
# Primero, creamos el usuario sin disponibilidad
POST http://localhost:3000/api/usuario HTTP/1.1
Content-Type: application/json

{
    "nombre": "Beatriz",
    "correo": "beatriz@live.u-tad.com",
    "password": "contraseña_segura",
    "nickname": "ProFisica",
    "instrumento": "violin",
    "bio": "Estudiante de U-tad",
    "grupos": []
}

###
# Luego, con el ID del usuario que obtuvimos de la respuesta anterior, creamos la disponibilidad
POST http://localhost:3000/api/disponibilidad HTTP/1.1
Content-Type: application/json

{
    "usuario": "65d6387c724634b5b0c64bfa",
    "lunes": [
        {"inicio": "10:00", "fin": "12:00"}
    ],
    "martes": [
        {"inicio": "09:00", "fin": "11:00"},
        {"inicio": "13:00", "fin": "15:00"},
        {"inicio": "16:00", "fin": "18:00"}
    ],
    "miercoles": [],
    "jueves": [
        {"inicio": "11:00", "fin": "13:00"},
        {"inicio": "14:00", "fin": "16:00"},
        {"inicio": "17:00", "fin": "19:00"}
    ],
    "viernes": [
        {"inicio": "09:00", "fin": "11:00"}
    ],
    "sabado": [],
    "domingo": []
}


###
# Finalmente, actualizamos el usuario con el ID de disponibilidad
# Esto asume que tienes un endpoint para actualizar usuarios
PUT http://localhost:3000/api/usuario/65d6387c724634b5b0c64bfa HTTP/1.1
Content-Type: application/json

{
    "disponibilidad": "65d63af2724634b5b0c64bfe" 
}
###
GET http://localhost:3000/api/usuario HTTP/1.1
